services:
  financial-transfer-scheduler-api:
    build: .
    container_name: financial-transfer-scheduler-api
    ports:
      - "8081:8081"
    depends_on:
      - h2
  h2:
    image: oscarfonts/h2
    container_name: h2-db
    ports:
      - "1521:1521"
      - "81:81"
    environment:
      H2_OPTIONS: '-ifNotExists'

  financial-transfer-scheduler-front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: financial-transfer-scheduler-front
    ports:
      - "8080:80"
    depends_on:
      - financial-transfer-scheduler-api